vich_uploader:
    db_driver: orm

    metadata:
        type: annotation

    mappings:
       video:
           uri_prefix: /uploads/videos
           upload_destination: '%kernel.project_dir%/public/uploads/videos'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            # inject_on_load: false
            # delete_on_update: true
            # delete_on_remove: true